version: '3.9'
services:
  app:
    build: .
    container_name: tcc_app
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: tcc_db
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
